# Render.com deployment configuration
services:
  - type: web
    name: orders-inventory-api
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements-render.txt
    startCommand: python run_server.py
    healthCheckPath: /health
    envVars:
      - key: WEBHOOK_SECRET
        value: production-webhook-secret-key-change-me
